version: '3'

services:
  docker-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=citydb
      - MYSQL_PASSWORD=password
    ports:
      - 3307:3306
  tomcat-db-api:
    image: mydist
    ports:
       - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/citydb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
        - docker-mysql

